branches:
  only:
    - source
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.57.2/hugo_0.57.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - git clone https://github.com/youngshook/hugo-theme-yinyang.git themes/yinyang
script:
  - hugo
after_script:
  - cd ./public
  - mv ../README.md .
  - echo 'blog.sker.me' > CNAME
  - git init
  - git config user.name "YoungShook"
  - git config user.email "shook.young@gmail.com"
  - git add .
  - git commit -m "Update By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
  - git push --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master --tags
  - cd ..
env:
 global:
   - GH_REF: github.com/youngshook/youngshook.github.io.git
notifications:
  email: false    # default notification method
  slack:
    battlestationgroup:ICYkSaOnazrtdAxujFfSEs0M
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"